# name: Test

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   Test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#           cache: 'yarn'

#       - name: Install dependencies
#         run: yarn i && yarn cypress install

#       - name: Validate
#         run: yarn run-p lint test:ci test:e2e:ci
#         env:
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

#       - name: Upload coverage
#         uses: codecov/codecov-action@v3
#         with:
#           fail_ci_if_error: true
